---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: golang:1.13-buster
    commands:
      - make test

  - name: lint
    image: cytopia/golint
    commands:
      - make lint

  - name: publish_linux_amd64
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-helm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
    when:
      branch:
        - master
      event: 
        - push

  - name: publish_linux_amd64_tag
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-helm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_TAG}
        - latest
    when:
      event: 
        - tag
---
kind: signature
hmac: 69cab5cc95f81984e2e9629c1f502fe4e69eb741b6c64770350bf3efa2eff86b

...
