---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: golangci/golangci-lint:v1.30.0-alpine
    commands:
      - apk update
      - apk add make
      - make test

  - name: snyk
    image: snyk/snyk:golang-1.14
    environment:
      SNYK_TOKEN:
        from_secret: snyk_token
    commands:
      - snyk monitor
    when:
      event: 
        - push

  - name: publish_linux_amd64
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-helm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
    when:
      branch:
        - master
      event:
        - push

  - name: publish_linux_amd64_tag
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-helm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_TAG}
    when:
      event:
        - tag
---
kind: signature
hmac: 8acd8d3c8bc817c2112fa860d78aede4eaffb45660b04d4cbf2628ef141f8c83

...
