---
kind: pipeline
type: kubernetes
name: test

trigger:
  branch:
    - master

resources:
  requests:
    cpu: 400
    memory: 2GiB

steps:
  - name: test
    image: golangci/golangci-lint:v1.56.0
    commands:
      - go mod download
      - make test
    resources:
      limits:
        memory: 3GiB
    when:
      event:
        - pull_request

---
kind: signature
hmac: 9b68b1fafcef4cc688232b0f78dddb07b4a84edb33d0f81a9534dfb0af8cf81d

...
