---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: golangci/golangci-lint:v1.48.0
    commands:
      - apk update
      - apk add make
      - make test

  - name: snyk
    image: snyk/snyk:golang-1.14
    environment:
      SNYK_TOKEN:
        from_secret: snyk_token
    commands:
      - snyk monitor
    when:
      event:
        - push

  - name: publish_linux_amd64
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-helm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
    when:
      branch:
        - master
      event:
        - push

  - name: publish_linux_amd64_tag
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/mongodb/drone-helm
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - ${DRONE_TAG}
        - v3
    when:
      event:
        - tag
---
kind: signature
hmac: 2666b1d537359a53e31312237bcfa97093e32a6c2d2901dbdf42aa8d6a5fec2e

...
