---
kind: pipeline
type: kubernetes
name: test

trigger:
  branch:
    - master

resources:
  requests:
    cpu: 400
    memory: 2GiB

steps:
  - name: test
    image: golangci/golangci-lint:v2.5.0
    commands:
      - go mod download
      - make test
    resources:
      limits:
        memory: 3GiB
    when:
      event:
        - pull_request

---
kind: signature
hmac: f764b029a88efb188e871fb9a2f5a3534109d3e575b416c9ee070e79571da0fc

...
