---
kind: pipeline
type: kubernetes
name: test

trigger:
  branch:
    - master

resources:
  requests:
    cpu: 400
    memory: 2GiB

steps:
  - name: test
    image: golangci/golangci-lint:v1.56.0
    environment:
      GOCACHE: /drone/src/gocache/
      GOLANGCI_LINT_CACHE: /drone/src/golangcilintcache/
    commands:
      - go mod download
      - make test
    resources:
      limits:
        memory: 3GiB
    when:
      event:
        - pull_request

  - name: snyk
    image: snyk/snyk:golang-1.21
    environment:
      SNYK_TOKEN:
        from_secret: snyk_token
    commands:
      - snyk monitor
    when:
      event:
        - pull_request
    depends_on:
      - test

---
kind: signature
hmac: 487ec88eb435f0a1e97e67c6604d60f6c1c87856d33cfe72aa8aeacc0deba677

...
